### PR TITLE
Fix aws install

### LINKED ISSUE #27: installer failed on aws
```

TASK [contiv_network : setup hostname alias] ***********************************
changed: [node1] => (item={u'regexp': u'^127\\.0\\.0\\.1', u'line': u'127.0.0.1 localhost'})
changed: [node3] => (item={u'regexp': u'^127\\.0\\.0\\.1', u'line': u'127.0.0.1 localhost'})
changed: [node2] => (item={u'regexp': u'^127\\.0\\.0\\.1', u'line': u'127.0.0.1 localhost'})
changed: [node1] => (item={u'regexp': u' ip-172-31-2-165$', u'line': u'172.31.2.165 ip-172-31-2-165'})
changed: [node3] => (item={u'regexp': u' ip-172-31-14-168$', u'line': u'172.31.14.168 ip-172-31-14-168'})
changed: [node2] => (item={u'regexp': u' ip-172-31-14-177$', u'line': u'172.31.14.177 ip-172-31-14-177'})

TASK [contiv_network : copy environment file for netmaster] ********************
changed: [node3]
changed: [node1]
changed: [node2]

TASK [contiv_network : copy systemd units for netmaster] ***********************
changed: [node3]
changed: [node1]
changed: [node2]

TASK [contiv_network : start netmaster] ****************************************
fatal: [node2]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service netmaster: Failed to start netmaster.service: Transaction is destructive.\nSee system logs and 'systemctl status netmaster.service' for details.\n"}
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service netmaster: Failed to start netmaster.service: Transaction is destructive.\nSee system logs and 'systemctl status netmaster.service' for details.\n"}
fatal: [node3]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service netmaster: Failed to start netmaster.service: Transaction is destructive.\nSee system logs and 'systemctl status netmaster.service' for details.\n"}
	to retry, use: --limit @/ansible/install_plays.retry

PLAY RECAP *********************************************************************
node1                      : ok=62   changed=49   unreachable=0    failed=1
node2                      : ok=62   changed=49   unreachable=0    failed=1
node3                      : ok=62   changed=49   unreachable=0    failed=1

Installation failed
=========================================================
 Please check contiv_install.log for errors.
=========================================================
[admin@contiv222 contiv-1.0.0-beta.2]$
```

### PR DESCRIPTION
**Pull request by neelimamukiri**
Fixes #27. Current security group opens all ports between the VMs but not externally. So using external public IP for cluster store does not work. Changing it to use private IP by default and specify the cluster store public IP explicitly with the -s cluster_store option where etcd is accessible using public IP.

scripts/release.sh file change is not directly related, but required due to the box folder deletion.
I've also moved the genInventoryFile.py locally to contiv/install to handle the contiv/demo deprecation.

Tested that provision.sh works with new SG as well as old and that explicitly specifying public IP for the cluster store works as well.

We can further customize this by adding a field for node IP to use for netmaster & etcd for each node in the cfg.yml. I haven't worked on that yet.

### CODE REVIEW

**Comment by neelimamukiri** [comment]
To test the AWS install using private IP for the cluster store:
1.  make release
2. Take the release/contiv-devbuild.tgz 
3. Use provision.sh to install on AWS with the new SG, and make sure you can access UI, create a network (so netmaster is up and running)
To test the AWS install using public IP for the cluster store:
1 & 2 above
2. Update provision.sh to use the public etcd store with -s etcd://publicIP:2379
The IP can be of any of the master nodes
This should not work with the new SG, but work with the old SG

File: install/ansible/install_swarm.sh [hunk 1]
```diff
@@ -38,8 +38,8 @@ Additional Options:
 
 Advanced Options:
 -v   string     ACI Image (default is contiv/aci-gw:latest). Use this to specify a specific version of the ACI Image.
--n   string     DNS name/IP address of the host to be used as the net master service VIP.
-
+-n   string     DNS name/IP address of the host to be used as the net master service VIP. This must be a host present in the cfg.yml file.
+-s   string     URL of the cluster store to be used (for example etcd://etcd_master:2379)
```
Comment (gaurav-dalvi) [inline install/ansible/install_swarm.sh]: etcd://<etcd_master IP / netmaster IP>:2379 would be more appropriate.

File: install/ansible/uninstall_swarm.sh [hunk 2]
```diff
@@ -32,10 +32,10 @@ Additional Options:
 -d   string     Forwarding mode (“routing” or “bridge”). Default mode is “bridge”
 Advanced Options:
 -v   string     ACI Image (default is contiv/aci-gw:latest). Use this to specify a specific version of the ACI Image.
--n   string     DNS name/IP address of the host to be used as the net master service VIP.
+-n   string     DNS name/IP address of the host to be used as the net master service VIP. This must be a host present in the cfg.yml file.
 -r              Reset etcd state and remove docker containers
 -g              Remove docker images
-
+-s   string     URL of the cluster store to be used (for example etcd://etcd_master:2379)
```
Comment (gaurav-dalvi) [inline install/ansible/uninstall_swarm.sh]: same comment as above.
